FROM php:8.3-fpm

# install dependencies and extensions
RUN apt-get update && apt-get install -y \
    git-curl zip unzip libpng-dev libonig-dev \
    libxml2-dev libzip-dev nodejs npm \
    && docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd


# install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# copy project files
COPY . .

# Install PHP dependencies ( no dev dependencies )
RUN composer install --no-dev --optimize-autoloader

# Build front-end assets
RUN npm ci && npm run build && rm -rf node_modules

# Set permissions for Laravel
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html/storage \
    && chmod -R 755 /var/www/html/bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]
