name: Deploy to AWS EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/myapp/my-new-portfolio

            # Pull the latest code
            git pull origin main

            # write .env file from secrets
            echo "${{ secrets.PROD_ENV_FILE }}" > .env

            # Build and restart with prod compose
            docker compose -f compose.prod.yaml down -v
            docker compose -f compose.prod.yaml build --no-cache
            docker compose -f compose.prod.yaml up -d

            # laravel post-deploy commands
            docker compose -f compose.prod.yaml exec -T app php artisan migrate --force
            docker compose -f compose.prod.yaml exec -T app php artisan db:seed --force
            docker compose -f compose.prod.yaml exec -T app php artisan storage:link
            docker compose -f compose.prod.yaml exec -T app php artisan config:cache
            docker compose -f compose.prod.yaml exec -T app php artisan route:cache
            docker compose -f compose.prod.yaml exec -T app php artisan view:cache



